_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 23
                - 55
            "4": 3.12.1
            "5": 0.19.4
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
